spring:
  application:
    name: auth

  grpc:
    server:
      port: 9090

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

jwt:
  secret:
    key: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff

member:
  url: http://localhost:8080

